### ISSUE TITLE
Implement env var substitution

### ISSUE THREAD

**Issue by DimmKirr** [blacktop/docker-kibana-alpine#3]
Is there any way to implement `_` to `.` substitution and lowercasing the parameters, as dots can cause some troubles in vars when used via bash.

so `HOST_NAME` becomes `host.name`

**Comment by blacktop** [comment]
I guess I could support both?  It would probably have to be like: `KIBANA_SETTING_SUBSETTING=VALUE` to make it easier to grep for in the `env`

**Comment by blacktop** [comment]
I added it to `latest/6.2/x-pack` let me know if it works and if it does feel free to close this issue.

https://github.com/blacktop/docker-kibana-alpine#customize-at-runtime-via-environment-variables

cheers

**Comment by DimmKirr** [comment]
Thank you. I think it should work. Any chance to push the image to dockerhub?

**Comment by blacktop** [comment]
It has been pushed to the dockerhub.  You will need to re-pull the images.
