### ISSUE TITLE
xpack has ownership bug in optimize folder

### ISSUE THREAD

**Issue by 0asp0** [blacktop/docker-kibana-alpine#4]
Hi,

if I substitute the kibana.yml kibana will start its optimize process again.
After you installed the xpack I got permission denied  for /usr/share/kibana/optimized.

You need to run the xpack installation as kibana user or you need to set the owner for kibana again, as you did before xpack installation.

**Comment by blacktop** [comment]
Whoa, I don't know why I didn't see this.  Is this still an issue?  What cmd are you running?

**Comment by blacktop** [comment]
It might make most sense to put it here: https://github.com/blacktop/docker-kibana-alpine/blob/master/6.2/docker-entrypoint.sh
